spring:
  application:
    name: documind

  datasource:
    url: jdbc:postgresql://localhost:5433/documind
    username: documind
    password: documind
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        generate_statistics: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6381

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.session.metrics: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics

documind:
  storage:
    location: ./storage/documents
  embedding:
    batch-size: 100
  rag:
    top-k: 5
    min-similarity: 0.25

