-- 업로드된 원본 파일
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    original_filename VARCHAR(255) NOT NULL ,
    stored_filename VARCHAR(255) NOT NULL UNIQUE ,
    content_hash CHAR(64) NOT NULL ,
    file_size BIGINT NOT NULL ,
    page_count INT ,
    extracted_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_documents_content_hash ON documents (content_hash);

-- 한 번의 처리 시도
CREATE TABLE embedding_jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id      BIGINT      NOT NULL REFERENCES documents (id),
    chunk_size       INT         NOT NULL,
    chunk_overlap    INT         NOT NULL,
    processing_mode  VARCHAR(20) NOT NULL,
    status           VARCHAR(20) NOT NULL,
    total_chunks     INT         NOT NULL DEFAULT 0,
    embedded_chunks  INT         NOT NULL DEFAULT 0,
    embedding_tokens BIGINT      NOT NULL DEFAULT 0,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    duration_ms      BIGINT,
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_chunk_overlap CHECK ( chunk_overlap >= 0 AND chunk_overlap < chunk_size)
);

CREATE INDEX idx_embedding_jobs_document_id ON embedding_jobs (document_id);

-- 청크 + 임베딩 벡터
CREATE SEQUENCE document_chunks_seq START 1 INCREMENT 50;

CREATE TABLE document_chunks (
    id BIGINT PRIMARY KEY ,
    job_id BIGINT NOT NULL REFERENCES embedding_jobs(id) ON DELETE CASCADE ,
    chunk_index INT NOT NULL ,
    content TEXT NOT NULL ,
    content_length INT NOT NULL ,
    page_number INT,
    embedding vector(1536),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_chunks_job_index UNIQUE (job_id, chunk_index)
);

CREATE INDEX idx_document_chunks_job_id ON document_chunks (job_id);

-- 질의 1건의 기록
CREATE TABLE query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    job_id BIGINT NOT NULL REFERENCES embedding_jobs (id),
    question TEXT NOT NULL ,
    answer TEXT,
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    retrieved_chunk_count INT,
    embedding_tokens INT NOT NULL DEFAULT 0,
    prompt_tokens INT NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    latency_ms BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_query_logs_create_at ON query_logs (created_at);

